name: Cleanup Expired Keys

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:       # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cleanup script
        run: python cleanup_keys.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add keys.json
          git commit -m "Remove expired keys" || echo "No changes to commit"
          git push



